language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - brasil.gov.addon/eggs
  - brasil.gov.contenttype/eggs
  - brasil.gov.tema/eggs
env:
  - TEMPLATE=addon
  - TEMPLATE=contenttype
  - TEMPLATE=tema
install:
  - python bootstrap.py
  - bin/buildout
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - bin/nosetests
  - bin/mrbob -O brasil.gov.$TEMPLATE --config test_answers_$TEMPLATE.ini ./bobtemplates/plonegovbr/$TEMPLATE
  - cd brasil.gov.$TEMPLATE
  - make tests
notifications:
  irc: irc.freenode.org#plonegovbr
