language: python
python: 2.7
install:
  - python bootstrap.py
  - bin/buildout
script:
  - bin/nosetests
  - bin/mrbob -O brasil.gov.addon --config test_answers_addon.ini ./bobtemplates/plonegovbr/addon
  - cd brasil.gov.addon
  - make tests
  - cd ..
  - bin/mrbob -O brasil.gov.tema --config test_answers_tema.ini ./bobtemplates/plonegovbr/tema
  - cd brasil.gov.tema
  - make tests
notifications:
  irc: irc.freenode.org#plonegovbr
